name: Find the Key!
description: |
  The end goal of the challenge is to find a key hidden in the target machine to capture the final flag.
  You will find hints and useful instruction scattered across the challenge. Have fun!
  **Connection Instructions**:
  
  $ `ssh -L localhost:<local port>:find_the_key:22 -p 56151 <username>@cs561.cs.umass.edu`

  SSH to labuser@localhost -p <local_port> with password labuser

  Please enclose the flag you found in CTF_SDaT{} before submitting.
  
value: 100
category: Miscellaneous
flag: CTF_SDaT{ex7uTWNjqfRTqz1dyPv}

# administrative
container_name: find_the_key
